name: Oberlin Steel
markdown: redcarpet
pygments: true
permalink: /albums/:title/
image_url: /static/images
baseurl: ""
prose:
  siteurl: 'http://oberlinsteel.com'
  media: 'static/media'
  metadata:
    albums/_posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "album"
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Name of file, must be in static/images/albums"
          type: "text"
      - name: "thumb"
        field:
          element: "checkbox"
          label: "Thumbnail"
          help: "If you have a smaller version of the image in static/images/albums-small"
          value: "false"
      - name: "year"
        element:
          field: "number"
          label: "year"
          type: "number"
      - name: "medium"
        element:
          field: "multiselect"
          value: "Medium"
          options:
          - name: 'CD'
            value: 'CD'
          - name: 'cassette'
            value: 'cassette'
          alterable: true
      - name: "cost"
        element:
          field: "text"
          label: "Cost"
          help: "In the format $10"
          placeholder: "$0"
          type: "text"
      - name: "paypal"
        element:
          field: "text"
          label: "PayPal code"
          help: "When you make a button, this is called value in the HTML. It looks like 37V6YCL34FQGA"
          type: "text"
      - name: "bandcamp"
        element:
          field: "text"
          label: "Bandcamp Link"
          help: "The part of the link that is the name of the album. It looks like welcome-to-the-swanktuary"
          type: "text"  