name: Oberlin Steel
markdown: redcarpet
pygments: true
permalink: /albums/:title/
image_url: /static/images
baseurl: ""
prose:
  siteurl: 'http://oberlinsteel.com'
  media: 'static/media'
  ignore:
    - /CNAME
    - /.gitignore
    - /README.md
    - /robots.txt
    - /static/css
    - /static/javascripts
    - /static/config.rb
    - /static/sass
    - /_includes
    - /_data
    - /_config.yml
  metadata:
    "":
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "bg"
        field:
          element: "text"
          label: "Background Image"
          help: "Name of file, must be in static/images/backgrounds. If you don't set this, it'll just be red."
          type: "text"
      - name: "heading"
        field:
          element: "text"
          label: "Heading (Optional)"
          help: "What it says at the top of the page. The title of this file is what goes in the name of the tab in the browser."
          type: "text"
      - name: "body-class"
        field: 
          element: "button"
          label: "Dark Photo?"
          help: "This makes the text boxes dark"
          on: "inverse"
          off: ""
    albums/_posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "album"
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Name of file, must be in static/images/albums"
          type: "text"
      - name: "thumb"
        field:
          element: "checkbox"
          label: "Thumbnail"
          help: "If you have a smaller version of the image in static/images/albums-small"
          value: "false"
      - name: "year"
        field:
          element: "number"
          label: "Year"
          help: "You don't need to list this for merch that doesn't have a year"
          type: "number"
      - name: "medium"
        field:
          element: "multiselect"
          label: "Medium"
          options:
          - name: 'CD'
            value: 'CD'
          - name: 'cassette'
            value: 'cassette'
          alterable: true
      - name: "cost"
        field:
          element: "text"
          label: "Cost, if available to buy"
          help: "In the format $10"
          placeholder: "$0"
          type: "text"
      - name: "paypal"
        field:
          element: "text"
          label: "PayPal code"
          help: "When you make a button, this is called value in the HTML. It looks like 37V6YCL34FQGA"
          type: "text"
      - name: "bandcamp"
        field:
          element: "text"
          label: "Bandcamp Link"
          help: "The part of the link that is the name of the album. It looks like welcome-to-the-swanktuary"
          type: "text"  
